name: Build and deploy Jekyll 4.2 site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: "16"
      # - run: npm install
      # - uses: helaili/jekyll-action@v2
      #   with:
      #     token: ${{ secrets.BUILD_TOKEN }}
      #     target_branch: "prod"
      # - run: NODE_ENV=production JEKYLL_ENV=production bundle exec jekyll build
      name: Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      name: ðŸš€ deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: prod

          
